---
output_dir: "output/{{ lab_id }}"

xcon:
 links:
  - p1
  - p2
  - pe1
  - pe2
  - cea1
  - ceb1

 p2p:
  - { a_device: 'p1', a_port: '1', b_device: 'pe1', b_port: '1' }
  - { a_device: 'p1', a_port: '2', b_device: 'pe2', b_port: '1' }
  - { a_device: 'p2', a_port: '1', b_device: 'pe1', b_port: '2' }
  - { a_device: 'p2', a_port: '2', b_device: 'pe2', b_port: '2' }
  - { a_device: 'pe1', a_port: '3', b_device: 'cea1', b_port: '1' }
  - { a_device: 'pe2', a_port: '3', b_device: 'ceb1', b_port: '1' }
